defaults:
  - base
  - _self_

_target_: proteinfoundation.nn.confidence.plddt_sequence_only_head.SequenceOnlyPLDDTHead
token_dim: 768
pair_repr_dim: 256
num_plddt_bins: 50
bin_min: 0.0
bin_max: 100.0
trunk:
  n_blocks: 1
  use_tri_mult: False
  use_tri_attn: False
