# @package _global_
defaults:
  - /nn/confidence/plddt_head@confidence.head
  - /dataset/unified/afdb_monomers_with_plddt@data
  - /training/confidence_distill@training
  - _self_

trainer:
  accelerator: gpu
  devices: 1
  strategy: ddp_find_unused_parameters_false
  precision: ${training.precision}
  max_epochs: ${training.max_epochs}
  gradient_clip_val: ${training.gradient_clip_val}
  log_every_n_steps: 25
  check_val_every_n_epoch: 1

seed: 42
run_name: "plddt-distill-swissprot"
